import { type TechStackItemProps } from "../interface/types"
import { 
  SiCss, 
  SiCplusplus, 
  SiPhp, 
  SiTypescript, 
  SiSharp, 
  SiPython, 
  SiJavascript, 
  SiPostgresql, 
  SiDjango, 
  SiXampp, 
  SiPytest, 
  SiDocker, 
  SiGithubactions, 
  SiGit, 
  SiPostman, 
  SiVercel, 
  SiHostinger, 
  SiArduino,
  SiRaylib 
} from "@icons-pack/react-simple-icons";
import { TbApi, TbTestPipe } from "react-icons/tb";

export const techStacks : TechStackItemProps[] = [
    {
        field:'languages',
        name:'css3',
        icon: <SiCss />,
        color:"#512BD4",
    },
    {
        field:'languages',
        name:'C++',
        icon:<SiCplusplus />,
        color:"#512BD4",
    },
    {
        field:'languages',
        name:'PHP',
        icon:< SiPhp />,
        color:"#512BD4",
    },
    {
        field:'languages',
        name:'typescript.js',
        icon:<SiTypescript />,
        color:"#512BD4",
    },
    {
        field:'languages',
        name:'C#',
        icon:<SiSharp />,
        color:"#512BD4",
    },
    {
        field:'languages',
        name:'Python',
        icon:<SiPython />,
        color:"#512BD4",
    },
    {
        field:'languages',
        name:'javaScript',
        icon:<SiJavascript />,
        color:"#512BD4",
    },
    {
        field:'database',
        name:'SQL',
        icon:<SiPostgresql />,
        color:"#512BD4",
    },
    {
        field:'frameworks',
        name:'django',
        icon:<SiDjango />,
        color:"#512BD4",
    },
    {
        field:'frameworks',
        name:'REST api',
        icon:<SiCss />,
        color:"#512BD4",
    },
    {
        field:'database',
        name:'xampp',
        icon:<SiXampp />,
        color:"#512BD4",
    },
    {
        field:'testing',
        name:'xUnit',
        icon:<SiCss />,
        color:"#512BD4",
    },
    {
        field:'testing',
        name:'pytest',
        icon:<SiPytest />,
        color:"#512BD4",
    },
    {
        field:'devops',
        name:'docker',
        icon:<SiDocker />,
        color:"#512BD4",
    },
    {
        field:'devops',
        name:'Github Actions',
        icon:<SiGithubactions />,
        color:"#512BD4",
    },
    {
        field:'tools',
        name:'Git',
        icon:<SiGit />,
        color:"#512BD4",
    },
    {
        field:'tools',
        name:'postman',
        icon:<SiPostman />,
        color:"#512BD4",
    },
    {
        field:'deployment',
        name:'Vercel',
        icon:<SiVercel />,
        color:"#512BD4",
    },
    {
        field:'deployment',
        name:'Hostinger',
        icon:<SiHostinger />,
        color:"#512BD4",
    },
    {
        field:'hardware&systems',
        name:'Raylib',
        icon:<SiRaylib />,
        color:"#512BD4",
    },
    {
        field:'hardware&systems',
        name:'Arduino',
        icon:<SiArduino />,
        color:"#512BD4",
    },
]