import { type TechStackItemProps } from "../interface/types";
import { 
  SiCss, 
  SiCplusplus, 
  SiPhp, 
  SiTypescript, 
  SiSharp, 
  SiPython, 
  SiJavascript, 
  SiPostgresql, 
  SiDjango, 
  SiXampp, 
  SiPytest, 
  SiDocker, 
  SiGithubactions, 
  SiGit, 
  SiPostman, 
  SiVercel, 
  SiHostinger, 
  SiArduino,
  SiRaylib ,
  SiReact,
  SiHtml5,
  SiTailwindcss,
  SiSqlite,
  SiYaml,
} from "@icons-pack/react-simple-icons";

export const techStacks: TechStackItemProps[] = [
     {
        field: 'languages',
        name: 'C#',
        icon: <SiSharp />,
        color: "#239120",
    },
    {
        field: 'languages',
        name: 'Python',
        icon: <SiPython />,
        color: "#3776AB",
    },
    {
        field: 'languages',
        name: 'javaScript',
        icon: <SiJavascript />,
        color: "#F7DF1E",
    },
    {
        field: 'languages',
        name: 'typescript.js',
        icon: <SiTypescript />,
        color: "#3178C6",
    },
    {
        field: 'languages',
        name: 'HTML',
        icon: <SiHtml5 />,
        color: "#E34F26",
    },
    {
        field: 'languages',
        name: 'css3',
        icon: <SiCss />,
        color: "#1572B6",
    },
    {
        field: 'languages',
        name: 'C++',
        icon: <SiCplusplus />,
        color: "#00599C",
    },
    {
        field: 'languages',
        name: 'PHP',
        icon: <SiPhp />,
        color: "#777BB4",
    },
    {
        field: 'database',
        name: 'SQL',
        icon: <SiSqlite />,
        color: "#4169E1",
    },
    {
        field: 'database',
        name: 'SQLite',
        icon: <SiSqlite />,
        color: "#4169E1",
    },
    {
        field: 'frameworks',
        name: 'django',
        icon: <SiDjango />,
        color: "#092E20",
    },
    {
        field: 'frameworks',
        name: 'tailwindCSs',
        icon: <SiTailwindcss />,
        color: "#06B6D4",
    },
    {
        field: 'frameworks',
        name: 'react',
        icon: <SiReact />,
        color: "#61DAFB",
    },
    {
        field: 'frameworks',
        name: 'REST api',
        icon: <SiCss />,
        color: "#009688",
    },
    {
        field: 'database',
        name: 'xampp',
        icon: <SiXampp />,
        color: "#FB7A24",
    },
    {
        field: 'testing',
        name: 'xUnit',
        icon: <SiCss />,
        color: "#512BD4",
    },
    {
        field: 'testing',
        name: 'pytest',
        icon: <SiPytest />,
        color: "#0A9EDC",
    },
    {
        field: 'devops',
        name: 'docker',
        icon: <SiDocker />,
        color: "#2496ED",
    },
    {
        field: 'devops',
        name: 'Github Actions',
        icon: <SiGithubactions />,
        color: "#2088FF",
    },
    {
        field: 'devops',
        name: 'YAML',
        icon: <SiYaml />,
        color: "#CB171E",
    },
    {
        field: 'tools',
        name: 'Git',
        icon: <SiGit />,
        color: "#F05032",
    },
    {
        field: 'tools',
        name: 'postman',
        icon: <SiPostman />,
        color: "#FF6C37",
    },
    {
        field: 'deployment',
        name: 'Vercel',
        icon: <SiVercel />,
        color: "#000000",
    },
    {
        field: 'deployment',
        name: 'Hostinger',
        icon: <SiHostinger />,
        color: "#673DE6",
    },
    {
        field: 'hardware&systems',
        name: 'Raylib',
        icon: <SiRaylib />,
        color: "#000000",
    },
    {
        field: 'hardware&systems',
        name: 'Arduino',
        icon: <SiArduino />,
        color: "#00979D",
    },
];